### PR TITLE
Updated contribution guidelines to utilize GitHub options

### PR DESCRIPTION
**Pull request by idinwoodie**
When users make a pull request, they are usually served a link to the repository's contribution guidelines, but the guidelines file must be named `CONTRIBUTING`. The changed filename in this patch will hopefully get more contributors to read the guidelines when submitting pull requests.

Additionally, I noticed that a majority of people aren't signing-off their commits. Hopefully with the updated guidelines filename more people will see the requirement. However, for those who view the requirement and don't understand what it is asking I added a line detailing the `git commit` options necessary to sign-off a commit.

Lastly, I updated to guidelines file to make use of the standard 80 character width for Markdown files.

### CODE REVIEW

**Comment by idinwoodie** [comment]
For reference: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by brasko** [comment]
This looks good, however, I would not like the text below,
 ### Developer's Certificate of Origin
reformatted, as it was taken from here,
 https://developercertificate.org/
and I'd prefer it to remain identical.

**Comment by idinwoodie** [comment]
Understood, I will revert the Developer's Certificate of Origin to remain identical to its source.

**Comment by idinwoodie** [comment]
@brasko all set!

**Pull request merged**
