### PR TITLE
nested functions

### PR DESCRIPTION
**Pull request by StefanoBelloni**
Hi,
I had the chance to compile cgdb on Mac Os X with clang 7.0.0 and I had problems compiling.
I eliminated the nested functions that were creating problems and a note in the INSTALL.

Stefano.

### CODE REVIEW

**Comment by brasko** [comment]
Hi Stefano!

I didn't get to look at the patch yet, but I can't accept it unless
you sign off on it. With git you can use that with -s.

This tells us you approve the license policy.
Please see CONTRIBUTE.md for more details on this.

Thanks,
Bob Rossi

**Comment by brasko** [comment]
Hi Stefano,

Please fix the merge conflicts and sign off on the existing commits. You'll have to force
push your changes probably to accomplish this.

Thanks,
Bob Rossi

**Comment by brasko** [comment]
I think this has been resolved when I got cgdb to compile with -pedantic.
Let me know otherwise.

**Comment by StefanoBelloni** [comment]
Hi.
I confirm it is resolved.

**Pull request closed without merging**
