### PR TITLE
Rename test directory to testsuite to fix `make check`

### PR DESCRIPTION
**Pull request by ibuclaw**
DejaGnu expects this to be the location where all tests exist, otherwise runtest dies before testing anything.

```
Looking for tool-and-target-specific interface file testsuite/config/unix.exp
Looking for tool-and-target-specific interface file testsuite/config/gnu.exp
Looking for tool-and-target-specific interface file testsuite/config/default.exp
Looking for tool-and-target-specific interface file testsuite/config/unknown.exp
Looking for tool-and-target-specific interface file testsuite/../config/unix.exp
Looking for tool-and-target-specific interface file testsuite/../config/gnu.exp
Looking for tool-and-target-specific interface file testsuite/../config/default.exp
Looking for tool-and-target-specific interface file testsuite/../config/unknown.exp
Looking for tool-and-target-specific interface file testsuite/../../config/unix.exp
Looking for tool-and-target-specific interface file testsuite/../../config/gnu.exp
Looking for tool-and-target-specific interface file testsuite/../../config/default.exp
Looking for tool-and-target-specific interface file testsuite/../../config/unknown.exp
Looking for tool-and-target-specific interface file testsuite/../../../config/unix.exp
Looking for tool-and-target-specific interface file testsuite/../../../config/gnu.exp
Looking for tool-and-target-specific interface file testsuite/../../../config/default.exp
Looking for tool-and-target-specific interface file testsuite/../../../config/unknown.exp
WARNING: Couldn't find tool config file for unix, using default.
WARNING: could not find testsuite; trying ../../test.
Top level testsuite dirs are ../../test
Running ../../test/kui.base/basic.exp ...
ERROR: (DejaGnu) proc "kui_start --file=/tmp/map.txt" does not exist.
The error code is TCL LOOKUP COMMAND kui_start
The info on the error is:
invalid command name "kui_start"
    while executing
"::tcl_unknown kui_start --file=/tmp/map.txt"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 ::tcl_unknown $args"
ERROR: tcl error sourcing ../../test/kui.base/basic.exp.
ERROR: tcl error code TCL LOOKUP COMMAND kui_start
ERROR: invalid command name "kui_start"
```

### CODE REVIEW

**Comment by brasko** [comment]
I just need you to sign off on this before i pull it in.

**Comment by ibuclaw** [comment]
I thought I did, done now.

**Comment by brasko** [comment]
I don't ever recall running into this issue, but it seems simple enough, so i've integrated it. thanks.

**Comment by ibuclaw** [comment]
> I don't ever recall running into this issue, but it seems simple enough, so i've integrated it. thanks.

I had a read up, and it even says this in their documentation.

https://www.gnu.org/software/dejagnu/manual/Adding-a-new-testsuite.html

**Pull request closed without merging**
