### PR TITLE
Fortran syntax highlighting

### PR DESCRIPTION
**Pull request by vlachoudis**

### CODE REVIEW

**Comment by brasko** [comment]
hi @vlachoudis , i know it's been a while, but are you still interested in this? If so, i can help you get this in. (although i haven't reviewed the patch yet)

**Comment by vlachoudis** [comment]
Hi @brasko 
In my work I have to deal with fortran code, so I am using it with my branch all the time. (always in sync with the latest cgdb)

**Comment by brasko** [comment]
OK. Great. @vlachoudis  Can you please signoff on your commits?

https://github.com/cgdb/cgdb/blob/master/CONTRIBUTING.md

**Comment by vlachoudis** [comment]
I've made a new pull request 355 with your changes
so I am closing this one

**Pull request closed without merging**
