### PR TITLE
Draft implementation for cmake

### PR DESCRIPTION
**Pull request by bmorel**
Pushed to show what it looks like currently, related to #281 

If the answer to use cmake is "no", no problem, one can always close this PR (it's a draft for that reason after all).

### CODE REVIEW

**Comment by bmorel** [comment]
This draft still works after recent rebasing. Waiting for more discussion on #281 about how much wanted this is, maybe comments on the `CMakeLists.txt` file itself. There's more that can be cleaned up though, if #288 was merged before.
Or, it could be done the other way: merge both those, and then do the cleanup, that might be easier, since it's just about removing the obvious `add_definitions` lines in this PR.

The `config.h.in` file could probably use some work, like using real mechanism to get the data in: what would be needed is to use `$(git describe)` in a target to generate the `config.h` file, which would depend on `.git/index` so that the file would be regenerated automatically on each git action. That's a mechanism I've seen nowhere though, just thought about this solution while writing this.

Other points are, to define which are exactly the project's requirements in term of portability. To me, if C++11 is required, there seems to be no reason to support OSes older than POSIX-2008, all that could simplify even the actual build system and source code files.

The question is, should I do the work, or not?

**Comment by brasko** [comment]
I am motivated to see this move forward. It's just that cgdb has used autoconf for so longer I'm quite nervous about making the change. Do you think it's appropriate to open an issue on the issues page and to see what others think?

**Comment by bmorel** [comment]
> Do you think it's appropriate to open an issue on the issues page and to see what others think?

Like #281 ?
I'm okay (eager, even, since I use that tool so much, I'd love to make a useful contribution) to finish the work so that it would not only work, but also be clean(er). Current status (or rather, last time I checked) this PR builds fine, but I'll admit I didn't cared much about either cleaniness or systems without pkg-config.

In my opinion, even if this works fine, I think preliminary specifications in what is required to actually use cgdb (posix standard, version of C++, that kind of things) would allow unrelated code cleanups, which will in turn make this PR (less useful but) easier to clean.
Long time I've not looked at it, but from top of my head, there's more than a few things which are about supporting pre C99 standard implementations (checking if stdio.h exists, for example...) or pre-POSIX-2003 (some other kinds of header checks or functions in those).
Those checks may make sense on (very) old systems, but then, cgdb requires C++11 IIRC (which is still not really shiny new, as old as it makes me feel) so I think they're stupid and makes everything more complicated for nothing. Including the autotools code.

**Comment by bmorel** [comment]
ping @brasko

**Pull request closed without merging**
