### PR TITLE
Added 'nexti' and 'stepi' commands to CGDB mode

### PR DESCRIPTION
**Pull request by jmuchemb**

### CODE REVIEW

**Comment by skywind3000** [comment]
I really need these

**Comment by idinwoodie** [comment]
@jmuchemb you need to sign off your commits for the patch to be considered.

**Comment by jmuchemb** [comment]
Oops. I've just rebased with Signed-off-by.

**Comment by brasko** [comment]
This patch looks good, it will just need to be redone on top of master. Any chance you have a desire to do that?

**Comment by jmuchemb** [comment]
Patch rebased on top of master.

**Review by iandinwoodie — APPROVED** [review]

**Comment by iandinwoodie** [comment]
@brasko runs clean and is signed off

**Comment by brasko** [comment]
Thanks! I'll integrate this before doing any other work on cgdb, but it may not be until this weekend.

**Comment by brasko** [comment]
I merged this into master. Thanks.

**Pull request closed without merging**
