### PR TITLE
Malloc size issues + savebuf command + if_display_warning

### PR DESCRIPTION
**Pull request by mikesart**
Fix malloc issues with -1 being passed in for sizes and add 'savebuf' command

I've found the savebuf command to be useful for saving output and then editing.

Feel free to cherry-pick and/or modify however you want, of course.. Thanks.

### CODE REVIEW

**Comment by brasko** [comment]
hi mike, i love this idea. I've wanted the savebuf feature for a long time. Can you think of a more vim like command for it? I was wondering if :w is good, considering i don't think we'd ever save off the file, as it's non editable.

**Comment by mikesart** [comment]
> hi mike, i love this idea. I've wanted the savebuf feature for a long time. Can you think of a more vim like command for it? I was wondering if :w is good, considering i don't think we'd ever save off the file, as it's non editable.

Great idea - switched to ":w" and ":write".

Also, it looks like "if_print_message" is going to need some love with the vterm changes. It appears they need CR and LFs, and possibly some way to refresh the prompt. In any case, give this a try when you get a chance and I can look at if_print_message separately if you want. Thanks Bob!

**Comment by mikesart** [comment]
Also added first pass at this:

>    Add if_display_warning() function
>
>    Same as if_display_message, except warning will
>      override message and be displayed only until user
>      hits any key.
>
>    if_print_message() was writing to CGDB buffer and getting that to play
>    nicely with GDB prompt and vterm appears to be a losing battle.
>
>    if_display_message and if_display_warning are varargs now as well

You can see and play with this feature by doing things like:

>  :write foobar
>  :write "/tmpx/foobar"
>  :write "/tmp/foobar"

Thanks Bob!

**Comment by brasko** [comment]
This time of year is crazy for me. I assure you i'll work on getting this integrated before the release.

Thanks!

**Comment by mikesart** [comment]
Thanks for the update, and no worries. I’ve got it integrated locally so feel free to proceed however works best on your side. Thanks!

**Pull request closed without merging**
